package org.yah.games.glsupport.context.enums;

import org.lwjgl.glfw.GLFW;

public enum WindowHint implements GLFWEnum {
    GLFW_RESIZABLE(GLFW.GLFW_RESIZABLE),
    GLFW_VISIBLE(GLFW.GLFW_VISIBLE),
    GLFW_DECORATED(GLFW.GLFW_DECORATED),
    GLFW_FOCUSED(GLFW.GLFW_FOCUSED),
    GLFW_AUTO_ICONIFY(GLFW.GLFW_AUTO_ICONIFY),
    GLFW_FLOATING(GLFW.GLFW_FLOATING),
    GLFW_MAXIMIZED(GLFW.GLFW_MAXIMIZED),
    GLFW_CENTER_CURSOR(GLFW.GLFW_CENTER_CURSOR),
    GLFW_TRANSPARENT_FRAMEBUFFER(GLFW.GLFW_TRANSPARENT_FRAMEBUFFER),
    GLFW_FOCUS_ON_SHOW(GLFW.GLFW_FOCUS_ON_SHOW),
    GLFW_SCALE_TO_MONITOR(GLFW.GLFW_SCALE_TO_MONITOR),
    GLFW_RED_BITS(GLFW.GLFW_RED_BITS),
    GLFW_GREEN_BITS(GLFW.GLFW_GREEN_BITS),
    GLFW_BLUE_BITS(GLFW.GLFW_BLUE_BITS),
    GLFW_ALPHA_BITS(GLFW.GLFW_ALPHA_BITS),
    GLFW_DEPTH_BITS(GLFW.GLFW_DEPTH_BITS),
    GLFW_STENCIL_BITS(GLFW.GLFW_STENCIL_BITS),
    GLFW_ACCUM_RED_BITS(GLFW.GLFW_ACCUM_RED_BITS),
    GLFW_ACCUM_GREEN_BITS(GLFW.GLFW_ACCUM_GREEN_BITS),
    GLFW_ACCUM_BLUE_BITS(GLFW.GLFW_ACCUM_BLUE_BITS),
    GLFW_ACCUM_ALPHA_BITS(GLFW.GLFW_ACCUM_ALPHA_BITS),
    GLFW_AUX_BUFFERS(GLFW.GLFW_AUX_BUFFERS),
    GLFW_SAMPLES(GLFW.GLFW_SAMPLES),
    GLFW_REFRESH_RATE(GLFW.GLFW_REFRESH_RATE),
    GLFW_STEREO(GLFW.GLFW_STEREO),
    GLFW_SRGB_CAPABLE(GLFW.GLFW_SRGB_CAPABLE),
    GLFW_DOUBLEBUFFER(GLFW.GLFW_DOUBLEBUFFER),
    GLFW_CLIENT_API(GLFW.GLFW_CLIENT_API),
    GLFW_CONTEXT_CREATION_API(GLFW.GLFW_CONTEXT_CREATION_API),
    GLFW_CONTEXT_VERSION_MAJOR(GLFW.GLFW_CONTEXT_VERSION_MAJOR),
    GLFW_CONTEXT_VERSION_MINOR(GLFW.GLFW_CONTEXT_VERSION_MINOR),
    GLFW_CONTEXT_ROBUSTNESS(GLFW.GLFW_CONTEXT_ROBUSTNESS),
    GLFW_CONTEXT_RELEASE_BEHAVIOR(GLFW.GLFW_CONTEXT_RELEASE_BEHAVIOR),
    GLFW_OPENGL_FORWARD_COMPAT(GLFW.GLFW_OPENGL_FORWARD_COMPAT),
    GLFW_OPENGL_DEBUG_CONTEXT(GLFW.GLFW_OPENGL_DEBUG_CONTEXT),
    GLFW_OPENGL_PROFILE(GLFW.GLFW_OPENGL_PROFILE),
    GLFW_COCOA_RETINA_FRAMEBUFFER(GLFW.GLFW_COCOA_RETINA_FRAMEBUFFER),
    GLFW_COCOA_FRAME_NAME(GLFW.GLFW_COCOA_FRAME_NAME),
    GLFW_COCOA_GRAPHICS_SWITCHING(GLFW.GLFW_COCOA_GRAPHICS_SWITCHING),
    GLFW_X11_CLASS_NAME(GLFW.GLFW_X11_CLASS_NAME),
    GLFW_X11_INSTANCE_NAME(GLFW.GLFW_X11_INSTANCE_NAME);

    private final int id;

    WindowHint(int id) {
        this.id = id;
    }

    @Override
    public int get() {
        return id;
    }
}
