package org.yah.games.glsupport.buffer.enums;

import org.yah.games.glsupport.GLEnum;
import org.yah.games.glsupport.context.GLContext;

public enum AttachmentPoint implements GLEnum {
    GL_COLOR_ATTACHMENT0(GLContext.GL_COLOR_ATTACHMENT0),
    GL_COLOR_ATTACHMENT1(GLContext.GL_COLOR_ATTACHMENT1),
    GL_COLOR_ATTACHMENT2(GLContext.GL_COLOR_ATTACHMENT2),
    GL_COLOR_ATTACHMENT3(GLContext.GL_COLOR_ATTACHMENT3),
    GL_COLOR_ATTACHMENT4(GLContext.GL_COLOR_ATTACHMENT4),
    GL_COLOR_ATTACHMENT5(GLContext.GL_COLOR_ATTACHMENT5),
    GL_COLOR_ATTACHMENT6(GLContext.GL_COLOR_ATTACHMENT6),
    GL_COLOR_ATTACHMENT7(GLContext.GL_COLOR_ATTACHMENT7),
    GL_COLOR_ATTACHMENT8(GLContext.GL_COLOR_ATTACHMENT8),
    GL_COLOR_ATTACHMENT9(GLContext.GL_COLOR_ATTACHMENT9),
    GL_COLOR_ATTACHMENT10(GLContext.GL_COLOR_ATTACHMENT10),
    GL_COLOR_ATTACHMENT11(GLContext.GL_COLOR_ATTACHMENT11),
    GL_COLOR_ATTACHMENT12(GLContext.GL_COLOR_ATTACHMENT12),
    GL_COLOR_ATTACHMENT13(GLContext.GL_COLOR_ATTACHMENT13),
    GL_COLOR_ATTACHMENT14(GLContext.GL_COLOR_ATTACHMENT14),
    GL_COLOR_ATTACHMENT15(GLContext.GL_COLOR_ATTACHMENT15),
    GL_COLOR_ATTACHMENT16(GLContext.GL_COLOR_ATTACHMENT16),
    GL_COLOR_ATTACHMENT17(GLContext.GL_COLOR_ATTACHMENT17),
    GL_COLOR_ATTACHMENT18(GLContext.GL_COLOR_ATTACHMENT18),
    GL_COLOR_ATTACHMENT19(GLContext.GL_COLOR_ATTACHMENT19),
    GL_COLOR_ATTACHMENT20(GLContext.GL_COLOR_ATTACHMENT20),
    GL_COLOR_ATTACHMENT21(GLContext.GL_COLOR_ATTACHMENT21),
    GL_COLOR_ATTACHMENT22(GLContext.GL_COLOR_ATTACHMENT22),
    GL_COLOR_ATTACHMENT23(GLContext.GL_COLOR_ATTACHMENT23),
    GL_COLOR_ATTACHMENT24(GLContext.GL_COLOR_ATTACHMENT24),
    GL_COLOR_ATTACHMENT25(GLContext.GL_COLOR_ATTACHMENT25),
    GL_COLOR_ATTACHMENT26(GLContext.GL_COLOR_ATTACHMENT26),
    GL_COLOR_ATTACHMENT27(GLContext.GL_COLOR_ATTACHMENT27),
    GL_COLOR_ATTACHMENT28(GLContext.GL_COLOR_ATTACHMENT28),
    GL_COLOR_ATTACHMENT29(GLContext.GL_COLOR_ATTACHMENT29),
    GL_COLOR_ATTACHMENT30(GLContext.GL_COLOR_ATTACHMENT30),
    GL_COLOR_ATTACHMENT31(GLContext.GL_COLOR_ATTACHMENT31);

    public static final int COUNT = values().length;

    private final int id;

    AttachmentPoint(int id) {
        this.id = id;
    }

    @Override
    public int get() {
        return id;
    }
}
